const STORAGE='palletOpsPrototypeV07';
const PREV_STORAGE='palletOpsPrototypeV06';
const LM_HANDOFF='palletOpsLoadmasterHandoff';
const initialState={
  settings:{historyDays:60,nextOrderNumber:1},
  palletTemplates:[
    {id:'TPL-GEEK-4840',name:'48×40 – Geek Industrial',customer:'Geek Industrial',length:48,width:40,condition:'new',ways:'4-way',runners:3,runnerGrade:2,topBoards:[{width:4,qty:5,grade:2}],bottomBoards:[{width:4,qty:3,grade:2},{width:6,qty:2,grade:2}],maxHeight:13,canRotate:true},
    {id:'TPL-SUP-4840',name:'48×40 – Supply',customer:'Supply',length:48,width:40,condition:'new',ways:'2-way',runners:3,runnerGrade:2,topBoards:[{width:6,qty:7,grade:2}],bottomBoards:[{width:4,qty:5,grade:2}],maxHeight:10,canRotate:false}
  ],
  lumber:[
    {id:'L8G1',size:'2×4 × 8 ft',lengthFt:8,grade:1,qty:260,reserved:20,min:80},
    {id:'L8G2',size:'2×4 × 8 ft',lengthFt:8,grade:2,qty:620,reserved:110,min:180},
    {id:'L8G3',size:'2×4 × 8 ft',lengthFt:8,grade:3,qty:360,reserved:60,min:120},
    {id:'L10G1',size:'2×4 × 10 ft',lengthFt:10,grade:1,qty:140,reserved:15,min:50},
    {id:'L10G2',size:'2×4 × 10 ft',lengthFt:10,grade:2,qty:410,reserved:90,min:120},
    {id:'L12G2',size:'2×4 × 12 ft',lengthFt:12,grade:2,qty:310,reserved:80,min:100},
    {id:'L12G3',size:'2×4 × 12 ft',lengthFt:12,grade:3,qty:190,reserved:30,min:80},
    {id:'L16G2',size:'2×4 × 16 ft',lengthFt:16,grade:2,qty:165,reserved:35,min:60},
    {id:'L16G4',size:'2×4 × 16 ft',lengthFt:16,grade:4,qty:120,reserved:10,min:50}
  ],
  orders:[
    {id:'22421',customer:'Warehouse One',product:'40×48',qty:220,due:'Mañana',shipping:'factory',stage:'waiting_material',wood:'L12',woodNeed:190,palletSku:'40×48 STD',notes:'Orden de ejemplo bloqueada por material.'},
    {id:'22418',customer:'Auto Parts Midwest',product:'42×48',qty:140,due:'Hoy',shipping:'factory',stage:'cutting',wood:'L10',woodNeed:120,palletSku:'42×48 HD',notes:'Corte iniciado.'},
    {id:'22415',customer:'Industrial Parts LLC',product:'48×48',qty:95,due:'Hoy',shipping:'pickup',stage:'material_ready',wood:'L8',woodNeed:80,palletSku:'48×48 STD',notes:'Material cortado y listo para fabricar.'},
    {id:'22395',customer:'Cummins Inc.',product:'Carga mixta',qty:286,due:'Hoy',shipping:'factory',stage:'ready_load',wood:'L8',woodNeed:0,palletSku:'MIX-22395',trailer:"53'",trailerWidth:96,trailerLength:628,notes:'Listo para optimizar carga.',loadItems:[
      {name:'145×26',length:145,width:26,quantity:35,maxHeight:10,canRotate:false},
      {name:'120×24',length:120,width:24,quantity:15,maxHeight:10,canRotate:false},
      {name:'102×24',length:102,width:24,quantity:20,maxHeight:10,canRotate:false},
      {name:'86×24',length:86,width:24,quantity:20,maxHeight:10,canRotate:true},
      {name:'72×24',length:72,width:24,quantity:20,maxHeight:10,canRotate:true},
      {name:'52×52',length:52,width:52,quantity:50,maxHeight:13,canRotate:false},
      {name:'40×40',length:40,width:40,quantity:50,maxHeight:13,canRotate:false},
      {name:'48×40',length:48,width:40,quantity:2,maxHeight:1,canRotate:true},
      {name:'27×27',length:27,width:27,quantity:74,maxHeight:13,canRotate:false}
    ]},
    {id:'22402',customer:'DHL Supply Chain',product:'40×48',qty:168,due:'Hoy',shipping:'pickup',stage:'ready_load',wood:'L8',woodNeed:0,palletSku:'40×48 STD',trailer:'Cliente trae tráiler',trailerWidth:96,trailerLength:628,notes:'Cliente recogerá con su propio tráiler.',loadItems:[{name:'40×48',length:40,width:48,quantity:168,maxHeight:13,canRotate:true}]},
    {id:'22381',customer:'ABC Manufacturing',product:'42×48',qty:212,due:'Hoy',shipping:'factory',stage:'transit',wood:'L8',woodNeed:0,palletSku:'42×48 HD',trailer:"53'",notes:'Chofer en tránsito.'}
  ],
  finished:[
    {sku:'48×48 STD',qty:318,reserved:95},
    {sku:'40×48 STD',qty:460,reserved:168},
    {sku:'42×48 HD',qty:175,reserved:140},
    {sku:'48×40 STD',qty:286,reserved:286}
  ],
  history:[
    {id:'22310',customer:'Midwest Logistics',shipping:'pickup',completed:'05 Ago',evidence:'Firma + foto de factura'},
    {id:'22288',customer:'Supplier X',shipping:'factory',completed:'03 Ago',evidence:'Firma de entrega'}
  ],
  notifications:[
    {id:1,text:'Orden #22415: material listo para fabricación.',kind:'ok'},
    {id:2,text:'2×4 × 12 ft cerca del mínimo disponible.',kind:'warn'}
  ]
};
let state=loadState();
let currentView=(location.hash||'').replace('#','')||'inicio';
const views={
  ordenes:['Órdenes','Crear, buscar y revisar órdenes antes de pasar por producción.'],
  inicio:['Centro de control','Resumen de toda la operación y flujo entre etapas.'],
  madera:['Inventario de madera','Existencias, reservas, recepción y material realmente disponible.'],
  produccion:['Producción / Corte','Planifica, reserva madera, inicia cortes y libera material a fabricación.'],
  fabricacion:['Fabricación de pallets','Recibe material listo, inicia ensamblaje y libera pallets a carga.'],
  terminados:['Inventario de pallets terminados','Existencia fabricada, reservas y disponibilidad para órdenes.'],
  carga:['Carga y despacho','Órdenes listas, LoadMaster AI, recogida del cliente, evidencia y despacho.'],
  reportes:['Reportes y productividad','Indicadores de producción, inventario y despacho.'],
  historial:['Historial','Órdenes completadas y política de retención configurable.']
};
const el={content:document.getElementById('content'),title:document.getElementById('viewTitle'),subtitle:document.getElementById('viewSubtitle'),dialog:document.getElementById('dialog'),dialogTitle:document.getElementById('dialogTitle'),dialogSubtitle:document.getElementById('dialogSubtitle'),dialogBody:document.getElementById('dialogBody')};
function normalizeBoardRows(rows,fallbackQty=0,fallbackWidth=4){if(Array.isArray(rows)&&rows.length)return rows.map(r=>({width:Number(r.width)||4,qty:Math.max(0,Number(r.qty)||0),grade:Math.min(4,Math.max(1,Number(r.grade)||2))}));return fallbackQty?[{width:Number(fallbackWidth)||4,qty:Number(fallbackQty)||0,grade:2}]:[]}
function normalizeState(raw){
  const base=structuredClone(initialState),out=raw&&typeof raw==='object'?raw:base;
  out.settings={...base.settings,...(out.settings||{})};
  if(!Number.isFinite(Number(out.settings.nextOrderNumber))||Number(out.settings.nextOrderNumber)<1)out.settings.nextOrderNumber=1;
  if(!Array.isArray(out.palletTemplates))out.palletTemplates=structuredClone(base.palletTemplates);
  if(!Array.isArray(out.orders))out.orders=structuredClone(base.orders);
  if(!Array.isArray(out.lumber)||!out.lumber.some(x=>x.grade))out.lumber=structuredClone(base.lumber);
  out.lumber.forEach(x=>{x.grade=Math.min(4,Math.max(1,Number(x.grade)||2));x.lengthFt=Number(x.lengthFt)||Number((String(x.size).match(/(\d+(?:\.\d+)?)\s*ft/i)||[])[1])||8});
  out.palletTemplates=out.palletTemplates.map(t=>({...t,runnerGrade:Number(t.runnerGrade)||2,topBoards:normalizeBoardRows(t.topBoards,Number(t.topBoards)||0,t.boardWidth),bottomBoards:normalizeBoardRows(t.bottomBoards,Number(t.bottomBoards)||0,t.boardWidth)}));
  out.orders.forEach(o=>{if(!o.palletSpec&&parseProductMeasure(o.product)){o.palletSpec={ways:'4-way',runners:3,runnerGrade:2,topBoards:[{width:4,qty:5,grade:2}],bottomBoards:[{width:4,qty:3,grade:2}]}}});
  if(!Array.isArray(out.finished))out.finished=structuredClone(base.finished);
  if(!Array.isArray(out.history))out.history=structuredClone(base.history);
  if(!Array.isArray(out.notifications))out.notifications=structuredClone(base.notifications);
  return out;
}
function loadState(){try{const raw=localStorage.getItem(STORAGE)||localStorage.getItem(PREV_STORAGE);return normalizeState(raw?JSON.parse(raw):structuredClone(initialState))}catch{return structuredClone(initialState)}}
function nextOrderId(){const n=Math.max(1,Number(state.settings.nextOrderNumber)||1);state.settings.nextOrderNumber=n+1;return String(n).padStart(4,'0')}
function templateById(id){return (state.palletTemplates||[]).find(t=>t.id===id)}
function orderRef(o){return `#${o.id}${o.clientOrder?` · Cliente ${o.clientOrder}`:''}`}

function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function clone(x){return JSON.parse(JSON.stringify(x))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function metric(label,value,hint){return `<div class="metric"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`}
function pill(text,color='gray'){return `<span class="pill ${color}">${text}</span>`}
function stageLabel(s){return ({waiting_material:'Esperando material',cutting:'En corte',material_ready:'Material listo',building:'En fabricación',ready_load:'Listo para cargar',loading:'Cargando',transit:'En tránsito',completed:'Completado'})[s]||s}
function stageColor(s){return ({waiting_material:'red',cutting:'yellow',material_ready:'blue',building:'purple',ready_load:'green',loading:'yellow',transit:'pink',completed:'gray'})[s]||'gray'}
function progressFor(s){const seq=['waiting_material','cutting','material_ready','building','ready_load','transit'];let n=seq.indexOf(s)+1;if(s==='loading')n=5;if(s==='completed')n=6;return `<div class="progress-line">${[1,2,3,4,5,6].map(i=>`<span class="${i<=n?'done':''}"></span>`).join('')}</div>`}
function moduleCard(view,icon,name,desc){return `<article class="card module-card" data-go="${view}"><div class="icon">${icon}</div><h3>${name}</h3><p>${desc}</p></article>`}
function orderById(id){return state.orders.find(o=>o.id===id)}
function lumberById(id){return state.lumber.find(x=>x.id===id)}
function addNote(text,kind='ok'){state.notifications.unshift({id:Date.now(),text,kind});state.notifications=state.notifications.slice(0,8);save()}
function componentRequirements(spec){const qty=Math.max(1,Number(spec.qty)||1),out=[];if(Number(spec.runners)>0)out.push({label:'Runners',count:qty*Number(spec.runners),cutLength:Number(spec.length)||1,grade:Number(spec.runnerGrade)||2});for(const [side,rows] of [['Arriba',spec.topBoards||[]],['Abajo',spec.bottomBoards||[]]])for(const r of rows)if(Number(r.qty)>0)out.push({label:`${side} 1×${r.width}`,count:qty*Number(r.qty),cutLength:Number(spec.width)||1,grade:Number(r.grade)||2});return out}
function buildMaterialPlan(spec){const reqs=componentRequirements(spec),orders=[reqs.slice().sort((a,b)=>b.cutLength-a.cutLength),reqs.slice().sort((a,b)=>a.cutLength-b.cutLength),reqs.slice().sort((a,b)=>b.count-a.count)];let best=null;for(const reqOrder of orders){const avail=Object.fromEntries(state.lumber.map(x=>[x.id,Math.max(0,x.qty-x.reserved)])),alloc=[],shortages=[];let waste=0;for(const req of reqOrder){let remain=req.count;const opts=state.lumber.map(x=>{const raw=(Number(x.lengthFt)||8)*12,y=Math.floor(raw/req.cutLength);return {x,raw,y,w:y>0?(raw-y*req.cutLength)/y:1e9,exact:Number(x.grade)===req.grade}}).filter(o=>o.y>0&&Number(o.x.grade)<=req.grade&&avail[o.x.id]>0).sort((a,b)=>a.w-b.w||(b.exact-a.exact)||a.raw-b.raw);for(const o of opts){if(remain<=0)break;const pieces=Math.min(avail[o.x.id],Math.ceil(remain/o.y));if(!pieces)continue;const produced=Math.min(remain,pieces*o.y);alloc.push({stockId:o.x.id,stock:o.x.size,grade:o.x.grade,component:req.label,cutLength:req.cutLength,rawPieces:pieces,yieldPerPiece:o.y,produced,wasteIn:pieces*o.raw-produced*req.cutLength});avail[o.x.id]-=pieces;remain-=produced;waste+=pieces*o.raw-produced*req.cutLength}if(remain>0)shortages.push({...req,missing:remain})}const agg={};for(const a of alloc){agg[a.stockId]=(agg[a.stockId]||0)+a.rawPieces}const score=shortages.reduce((n,x)=>n+x.missing,0)*1e9+waste;const cand={allocations:alloc,stockTotals:agg,shortages,wasteIn:waste,totalRaw:Object.values(agg).reduce((a,b)=>a+b,0),requirements:reqs};if(!best||score<best.score)best={...cand,score}}return best||{allocations:[],stockTotals:{},shortages:[],wasteIn:0,totalRaw:0,requirements:reqs}}
function reserveWood(order){const plan=buildMaterialPlan({...order.palletSpec,qty:order.qty,length:order.loadItems?.[0]?.length||parseProductMeasure(order.product)?.length,width:order.loadItems?.[0]?.width||parseProductMeasure(order.product)?.width});if(plan.shortages.length){order.materialPlan=plan;return false}for(const [id,n] of Object.entries(plan.stockTotals)){const w=lumberById(id);if(!w||w.qty-w.reserved<n)return false}for(const [id,n] of Object.entries(plan.stockTotals))lumberById(id).reserved+=n;order.materialPlan=plan;order.materialReservation=plan.stockTotals;order.woodNeed=plan.totalRaw;save();return true}
function consumeReservedWood(order){for(const [id,n] of Object.entries(order.materialReservation||{})){const w=lumberById(id);if(!w)continue;w.qty=Math.max(0,w.qty-n);w.reserved=Math.max(0,w.reserved-n)}order.materialReservation={};save()}
function findFinished(sku){let f=state.finished.find(x=>x.sku===sku);if(!f){f={sku,qty:0,reserved:0};state.finished.push(f)}return f}
function parseProductMeasure(text){
  const m=String(text||'').match(/(\d+(?:\.\d+)?)\s*[×xX]\s*(\d+(?:\.\d+)?)/);
  return m?{length:Number(m[1]),width:Number(m[2])}:null;
}
function loadItemsFor(order){
  if(Array.isArray(order.loadItems)&&order.loadItems.length)return clone(order.loadItems);
  const m=parseProductMeasure(order.product);
  if(!m)return [];
  return [{name:`${m.length}×${m.width}`,length:m.length,width:m.width,quantity:Number(order.qty)||1,maxHeight:13,canRotate:true}];
}
function loadTotal(items){return (items||[]).reduce((n,x)=>n+(Number(x.quantity)||0),0)}

function renderInicio(){
  const active=state.orders.filter(o=>o.stage!=='completed').length, ready=state.orders.filter(o=>o.stage==='ready_load').length, prod=state.orders.filter(o=>['waiting_material','cutting','material_ready','building'].includes(o.stage)).length, low=state.lumber.filter(x=>x.qty-x.reserved<x.min).length;
  return `<div class="grid metrics">${metric('Órdenes activas',active,'En toda la operación')}${metric('Listas para cargar',ready,'Ya fabricadas y liberadas')}${metric('Producción en curso',prod,'Corte + fabricación')}${metric('Alertas de madera',low,'Debajo del mínimo disponible')}</div>
  <div class="section"><div class="section-head"><div><h2>Módulos</h2><p>Todos comparten las mismas órdenes; el prototipo permite moverlas por etapas.</p></div></div><div class="grid module-grid">${moduleCard('ordenes','＋','Órdenes','Crear una orden en dos pasos y reutilizar plantillas.')}${moduleCard('madera','▦','Inventario de madera','Recibir material, ver reservas y disponibilidad.')}${moduleCard('produccion','✂','Producción / Corte','Reservar madera, iniciar corte y liberar material.')}${moduleCard('fabricacion','⚒','Fabricación','Recibir aviso, armar pallets y liberarlos.')}${moduleCard('terminados','▣','Inventario de pallets','Producto terminado y reservado.')}${moduleCard('carga','▰','Carga y despacho','Optimizar, cargar, evidencia, firma y salida.')}${moduleCard('reportes','▥','Reportes','Resumen operativo sin crear menús innecesarios.')}</div></div>
  <div class="section grid two-col"><div class="card"><div class="section-head"><div><h2>Flujo real de una orden</h2><p>Cada botón mueve la misma orden al siguiente módulo.</p></div></div><div class="timeline"><span class="node">Inventario</span><span class="arrow">→</span><span class="node">Corte</span><span class="arrow">→</span><span class="node">Material listo</span><span class="arrow">→</span><span class="node">Fabricación</span><span class="arrow">→</span><span class="node">Carga</span><span class="arrow">→</span><span class="node">Historial</span></div><div style="height:14px"></div><button class="btn" data-go="ordenes">Crear / revisar órdenes</button></div><div class="card"><h2 style="font-size:17px;margin-top:0">Avisos automáticos</h2>${state.notifications.slice(0,4).map(n=>`<div class="notification ${n.kind==='ok'?'ok':''}" style="margin-bottom:8px">${n.text}</div>`).join('')||'<div class="small">Sin avisos.</div>'}</div></div>`
}
function renderMadera(){return `<div class="toolbar"><button class="btn" data-action="receiveWood">+ Recibir madera</button><button class="btn secondary" data-action="physicalCount">Conteo físico</button></div><div class="table-wrap"><table><thead><tr><th>Medida</th><th>Calidad</th><th>Existencia</th><th>Reservado</th><th>Disponible</th><th>Mínimo</th><th>Estado</th></tr></thead><tbody>${state.lumber.map(x=>{const a=x.qty-x.reserved;return `<tr><td><b>${x.size}</b></td><td><b>#${x.grade}</b><div class="small">${x.grade===1?'Mejor':x.grade===4?'Más baja':'Intermedia'}</div></td><td>${x.qty}</td><td>${x.reserved}</td><td>${a}</td><td>${x.min}</td><td>${a<x.min?pill('Bajo','yellow'):pill('Bien','green')}</td></tr>`}).join('')}</tbody></table></div><div class="section notification info"><b>Regla del prototipo:</b> el planificador solo usa largos y calidades que existan en inventario. Calidad #1 es mejor que #2, #3 y #4. Puede usar una calidad mejor que la requerida, nunca una peor.</div>`}
function orderMaterialSummary(o){const p=o.materialPlan||buildMaterialPlan({...o.palletSpec,qty:o.qty,length:o.loadItems?.[0]?.length||parseProductMeasure(o.product)?.length,width:o.loadItems?.[0]?.width||parseProductMeasure(o.product)?.width});if(p.shortages?.length)return `<span class="pill red">Falta material</span><div class="small">${p.shortages.map(x=>`${x.label}: faltan ${x.missing}`).join(' · ')}</div>`;const parts=Object.entries(p.stockTotals||{}).map(([id,n])=>{const w=lumberById(id);return `${n} × ${w?.size||id} #${w?.grade||'?'}`});return `<div>${parts.join('<br>')||'Sin plan'}</div><div class="small">${p.totalRaw||0} piezas madre · desperdicio lineal aprox. ${Math.round(p.wasteIn||0)} in</div>`}
function renderOrdenes(){const rows=state.orders.filter(o=>o.stage!=='completed');return `<div class="toolbar"><button class="btn" data-action="newOrder">+ Nueva orden</button><input id="ordersSearch" class="search-input" placeholder="Buscar # interno, orden cliente o cliente"></div><div class="table-wrap"><table><thead><tr><th>Orden</th><th>Cliente</th><th>Producto</th><th>Cantidad</th><th>Entrega</th><th>Estado</th></tr></thead><tbody>${rows.map(o=>{const search=[o.id,o.clientOrder,o.customer,o.product].filter(Boolean).join(' ').toLowerCase();return `<tr data-order-row data-search="${search.replace(/"/g,'&quot;')}"><td><b>#${o.id}</b>${o.clientOrder?`<div class="small">Cliente: ${o.clientOrder}</div>`:''}</td><td>${o.customer}</td><td>${o.product}</td><td>${o.qty}</td><td>${o.shipping==='pickup'?'Recogida cliente':'Envío fábrica'}</td><td>${pill(stageLabel(o.stage),stageColor(o.stage))}</td></tr>`}).join('')}</tbody></table></div><div class="section notification info"><b>Una sola entrada.</b> La orden se crea aquí y el mismo registro viaja por Corte → Fabricación → Carga → Historial.</div>`}
function renderProduccion(){const rows=state.orders.filter(o=>['waiting_material','cutting','material_ready'].includes(o.stage));return `<div class="toolbar"><button class="btn secondary" data-go="ordenes">Ir a Órdenes</button><button class="btn secondary" data-action="autoPlan">Recalcular planes de corte</button><input id="productionSearch" class="search-input" placeholder="Buscar # interno, orden cliente o cliente"></div><div class="table-wrap"><table><thead><tr><th>Orden</th><th>Cliente</th><th>Producto</th><th>Cantidad</th><th>Etapa</th><th>Plan automático de madera</th><th>Acción</th></tr></thead><tbody>${rows.map(o=>{let action=o.stage==='waiting_material'?`<button class="btn" data-cut-start="${o.id}">Reservar e iniciar corte</button>`:o.stage==='cutting'?`<button class="btn" data-cut-ready="${o.id}">Material listo</button>`:`<span class="small">Esperando fabricación</span>`;const search=[o.id,o.clientOrder,o.customer,o.product].filter(Boolean).join(' ').toLowerCase();return `<tr data-production-row data-search="${search.replace(/"/g,'&quot;')}"><td><b>#${o.id}</b>${o.clientOrder?`<div class="small">Cliente: ${o.clientOrder}</div>`:''}</td><td>${o.customer}</td><td>${o.product}</td><td>${o.qty}</td><td>${pill(stageLabel(o.stage),stageColor(o.stage))}</td><td>${orderMaterialSummary(o)}</td><td>${action}</td></tr>`}).join('')||'<tr><td colspan="7">No hay órdenes en esta etapa.</td></tr>'}</tbody></table></div><div class="section card"><b>Planificador de corte v0.7</b><p class="small">Ya no seleccionas manualmente 8, 10, 12 o 16 pies. El prototipo compara el inventario disponible, el rendimiento por corte y la calidad requerida, y escoge automáticamente la combinación con menos desperdicio lineal entre las opciones disponibles.</p></div>`}
function renderFabricacion(){const rows=state.orders.filter(o=>['material_ready','building'].includes(o.stage));return `<div class="grid metrics">${metric('Material listo',rows.filter(o=>o.stage==='material_ready').length,'Puede recogerlo el armador')}${metric('En fabricación',rows.filter(o=>o.stage==='building').length,'Trabajo activo')}${metric('Listas para carga',state.orders.filter(o=>o.stage==='ready_load').length,'Ya fabricadas')}${metric('Avisos',state.notifications.length,'Eventos recientes')}</div><div class="section table-wrap"><table><thead><tr><th>Orden</th><th>Cliente</th><th>Producto</th><th>Cantidad</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rows.map(o=>`<tr><td>#${o.id}</td><td>${o.customer}</td><td>${o.product}</td><td>${o.qty}</td><td>${pill(stageLabel(o.stage),stageColor(o.stage))}</td><td>${o.stage==='material_ready'?`<button class="btn" data-build-start="${o.id}">Iniciar fabricación</button>`:`<button class="btn" data-build-ready="${o.id}">Terminar y liberar</button>`}</td></tr>`).join('')||'<tr><td colspan="6">No hay órdenes en fabricación.</td></tr>'}</tbody></table></div><div class="section notification ok"><b>Aviso automático:</b> cuando Corte libera material, Fabricación lo ve aquí sin que nadie tenga que ir a avisar personalmente.</div>`}
function renderTerminados(){const total=state.finished.reduce((s,x)=>s+x.qty,0),res=state.finished.reduce((s,x)=>s+x.reserved,0);return `<div class="grid metrics">${metric('Fabricados',total,'Inventario actual')}${metric('Reservados',res,'Asignados a órdenes')}${metric('Disponibles',total-res,'Sin reservar')}${metric('Listos para carga',state.orders.filter(o=>o.stage==='ready_load').reduce((s,o)=>s+o.qty,0),'Pallets liberados')}</div><div class="section table-wrap"><table><thead><tr><th>SKU</th><th>Existencia</th><th>Reservado</th><th>Disponible</th></tr></thead><tbody>${state.finished.map(x=>`<tr><td><b>${x.sku}</b></td><td>${x.qty}</td><td>${x.reserved}</td><td>${x.qty-x.reserved}</td></tr>`).join('')}</tbody></table></div>`}
function shipPill(o){if(o.shipping==='pickup')return pill('Recogida del cliente','blue');if(o.stage==='transit')return pill('En tránsito','pink');return pill('Envío de fábrica','yellow')}
function renderCarga(){const rows=state.orders.filter(o=>o.stage!=='completed');return `<div class="toolbar"><button class="btn secondary" id="openLoadMaster">Abrir LoadMaster AI</button><input id="loadSearch" class="search-input" placeholder="Buscar # interno, orden cliente o cliente"><select><option>Todos</option><option>Envío de fábrica</option><option>Recogida del cliente</option><option>En tránsito</option></select></div><div class="grid two-col"><div><h2 style="font-size:16px">Pedidos y planificación de carga</h2>${rows.map(o=>{const ready=['ready_load','loading','transit'].includes(o.stage);const search=[o.id,o.clientOrder,o.customer,o.product].filter(Boolean).join(' ').toLowerCase();let action='';if(o.stage==='transit')action=`<button class="btn" data-transit-done="${o.id}">Marcar entregado</button>`;else if(ready)action=`<button class="btn" data-load-order="${o.id}">${o.stage==='loading'?'Continuar carga':(o.shipping==='pickup'?'Iniciar recogida':'Optimizar / iniciar carga')}</button>`;else action=`<button class="btn secondary" data-plan-load="${o.id}">Planear en LoadMaster</button><div class="small" style="margin-top:6px">Aún no se puede despachar: ${stageLabel(o.stage)}.</div>`;return `<div class="card order-card" data-load-card data-search="${search.replace(/"/g,'&quot;')}"><div class="order-card-top"><div>${shipPill(o)}<h3 style="margin:9px 0 3px">${o.customer}</h3><div class="small">Orden interna #${o.id}${o.clientOrder?` · Orden cliente ${o.clientOrder}`:''}</div><div class="small">${o.qty} pallets · ${o.product}</div>${progressFor(o.stage)}</div><div style="text-align:right"><div class="small">Estado</div><b>${stageLabel(o.stage)}</b><div style="height:8px"></div>${action}</div></div></div>`}).join('')||'<div class="empty-state">No hay pedidos.</div>'}</div><aside><div class="card"><h2 style="font-size:16px;margin-top:0">Planificación anticipada</h2><p class="small">Una orden aparece aquí desde que se crea. LoadMaster puede planearla antes de fabricar, pero los botones de carga y despacho solo se habilitan cuando Fabricación la libera.</p></div><div class="card" style="margin-top:12px"><h2 style="font-size:16px;margin-top:0">Colores de despacho</h2><div>${pill('Envío de fábrica','yellow')}<div class="small" style="margin:5px 4px 12px">La fábrica pone tráiler y chofer.</div>${pill('Recogida del cliente','blue')}<div class="small" style="margin:5px 4px 12px">El cliente llega con su propio tráiler.</div>${pill('En tránsito','pink')}<div class="small" style="margin:5px 4px">El chofer de la fábrica va camino al cliente.</div></div></div></aside></div>`}
function renderReportes(){const completed=state.history.length;return `<div class="grid metrics">${metric('Órdenes activas',state.orders.filter(o=>o.stage!=='completed').length,'Operación actual')}${metric('Pallets terminados',state.finished.reduce((s,x)=>s+x.qty,0),'Inventario')}${metric('Despachos históricos',completed,'En este demo')}${metric('Retención',state.settings.historyDays+' días','Configurable')}</div><div class="section grid two-col"><div class="card"><h2 style="font-size:16px;margin-top:0">Resumen por etapa</h2><div class="status-list">${['waiting_material','cutting','material_ready','building','ready_load','transit'].map(s=>`<div class="status-row"><span class="dot"></span><div>${stageLabel(s)}</div><b>${state.orders.filter(o=>o.stage===s).length}</b></div>`).join('')}</div></div><div class="card"><h2 style="font-size:16px;margin-top:0">Idea de producción sumario</h2><p class="small">Este módulo concentra la información de productividad sin obligar a crear un menú separado para cada reporte.</p></div></div>`}
function renderHistorial(){return `<div class="toolbar"><label class="small">Retención <select id="historyDays"><option value="30" ${state.settings.historyDays===30?'selected':''}>30 días</option><option value="60" ${state.settings.historyDays===60?'selected':''}>60 días</option><option value="90" ${state.settings.historyDays===90?'selected':''}>90 días</option></select></label></div><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Tipo</th><th>Completado</th><th>Evidencia</th></tr></thead><tbody>${state.history.map(h=>`<tr><td>#${h.id}${h.clientOrder?`<div class="small">Cliente: ${h.clientOrder}</div>`:''}</td><td>${h.customer}</td><td>${h.shipping==='pickup'?'Recogida cliente':'Envío fábrica'}</td><td>${h.completed}</td><td>${h.evidence}</td></tr>`).join('')||'<tr><td colspan="5">Sin historial.</td></tr>'}</tbody></table></div><div class="section notification">El prototipo guarda el historial en el navegador. En la plataforma real, la retención podrá archivar o purgar automáticamente según la política que se decida.</div>`}
function render(){const [t,s]=views[currentView];el.title.textContent=t;el.subtitle.textContent=s;el.content.innerHTML=({inicio:renderInicio,ordenes:renderOrdenes,madera:renderMadera,produccion:renderProduccion,fabricacion:renderFabricacion,terminados:renderTerminados,carga:renderCarga,reportes:renderReportes,historial:renderHistorial})[currentView]();bindDynamic()}
function navigate(v){currentView=v;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.getElementById('sidebar').classList.remove('open');render()}
function openDialog(title,subtitle,body){el.dialogTitle.textContent=title;el.dialogSubtitle.textContent=subtitle||'';el.dialogBody.innerHTML=body;el.dialog.showModal()}
function closeDialog(){el.dialog.close()}
function bindDynamic(){
  document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>navigate(x.dataset.go));
  document.querySelectorAll('[data-cut-start]').forEach(x=>x.onclick=()=>startCut(x.dataset.cutStart));
  document.querySelectorAll('[data-cut-ready]').forEach(x=>x.onclick=()=>finishCut(x.dataset.cutReady));
  document.querySelectorAll('[data-build-start]').forEach(x=>x.onclick=()=>startBuild(x.dataset.buildStart));
  document.querySelectorAll('[data-build-ready]').forEach(x=>x.onclick=()=>finishBuild(x.dataset.buildReady));
  document.querySelectorAll('[data-load-order]').forEach(x=>x.onclick=()=>openLoadOrder(x.dataset.loadOrder));
  document.querySelectorAll('[data-plan-load]').forEach(x=>x.onclick=()=>openLoadPreparation(x.dataset.planLoad));
  document.querySelectorAll('[data-transit-done]').forEach(x=>x.onclick=()=>completeDelivery(x.dataset.transitDone));
  document.getElementById('openLoadMaster')?.addEventListener('click',openLoadMaster);
  document.querySelector('[data-action="receiveWood"]')?.addEventListener('click',receiveWoodDialog);
  document.querySelector('[data-action="physicalCount"]')?.addEventListener('click',()=>toast('Prototipo: aquí se capturaría un conteo físico.'));
  document.querySelector('[data-action="newOrder"]')?.addEventListener('click',newOrderDialog);
  document.querySelector('[data-action="autoPlan"]')?.addEventListener('click',()=>{state.orders.filter(o=>o.stage==='waiting_material'&&o.palletSpec).forEach(o=>{o.materialPlan=buildMaterialPlan({...o.palletSpec,qty:o.qty,length:o.loadItems?.[0]?.length||parseProductMeasure(o.product)?.length,width:o.loadItems?.[0]?.width||parseProductMeasure(o.product)?.width});o.woodNeed=o.materialPlan.totalRaw});save();toast('Planes de material recalculados con inventario actual.');render()});
  document.getElementById('historyDays')?.addEventListener('change',e=>{state.settings.historyDays=Number(e.target.value);save();toast('Retención actualizada a '+e.target.value+' días.')});
  document.getElementById('ordersSearch')?.addEventListener('input',e=>filterBySearch('[data-order-row]',e.target.value));
  document.getElementById('productionSearch')?.addEventListener('input',e=>filterBySearch('[data-production-row]',e.target.value));
  document.getElementById('loadSearch')?.addEventListener('input',e=>filterBySearch('[data-load-card]',e.target.value));
}
function filterBySearch(selector,value){const q=String(value||'').trim().toLowerCase();document.querySelectorAll(selector).forEach(el=>{el.style.display=!q||String(el.dataset.search||'').includes(q)?'':'none'})}
function receiveWoodDialog(){openDialog('Recibir madera','Entrada de materia prima',`<div class="form-grid"><label><span>Medida</span><select id="rwSize">${state.lumber.map(x=>`<option value="${x.id}">${x.size} · calidad #${x.grade}</option>`).join('')}</select></label><label><span>Cantidad de piezas</span><input id="rwQty" type="number" min="1" value="100"></label></div><div class="dialog-actions"><button type="button" class="btn secondary" id="rwCancel">Cancelar</button><button type="button" class="btn" id="rwSave">Recibir</button></div>`);document.getElementById('rwCancel').onclick=closeDialog;document.getElementById('rwSave').onclick=()=>{const l=lumberById(document.getElementById('rwSize').value);l.qty+=Number(document.getElementById('rwQty').value)||0;save();closeDialog();toast('Madera recibida y disponible.');render()}}
function estimateOrderMaterial(spec){return buildMaterialPlan(spec)}
function boardRowsHtml(side,rows){return `<div class="board-editor" data-board-side="${side}"><div class="board-editor-head"><b>${side==='top'?'Tablas arriba':'Tablas abajo'}</b><button type="button" class="btn ghost" data-add-board="${side}">+ Agregar tipo de tabla</button></div>${rows.map((r,i)=>`<div class="board-row" data-board-row="${side}-${i}"><label><span>Tabla</span><select data-board-width><option value="4" ${Number(r.width)===4?'selected':''}>1×4</option><option value="6" ${Number(r.width)===6?'selected':''}>1×6</option></select></label><label><span>Cantidad por pallet</span><input data-board-qty type="number" min="0" value="${Number(r.qty)||0}"></label><label><span>Calidad requerida (1 mejor)</span><select data-board-grade>${[1,2,3,4].map(g=>`<option value="${g}" ${Number(r.grade)===g?'selected':''}>#${g}</option>`).join('')}</select></label><button type="button" class="remove-board" data-remove-board="${side}-${i}" aria-label="Eliminar tipo">×</button></div>`).join('')}</div>`}
function newOrderDialog(){
  const draft={internalId:String(Math.max(1,Number(state.settings.nextOrderNumber)||1)).padStart(4,'0'),customer:'',clientOrder:'',due:'',shipping:'pickup',condition:'new',notes:'',templateId:'',templateName:'',length:48,width:40,qty:10,ways:'4-way',runners:3,runnerGrade:2,topBoards:[{width:4,qty:5,grade:2}],bottomBoards:[{width:4,qty:3,grade:2},{width:6,qty:2,grade:2}],maxHeight:13,canRotate:true,saveTemplate:false};
  const phase1=()=>{openDialog('Nueva orden · Paso 1 de 2','Datos administrativos de la orden',`<div class="wizard-steps"><span class="wizard-step active">1 Orden</span><span class="wizard-step">2 Descripción del pallet</span></div><div class="notification info"><b>Orden interna #${draft.internalId}</b> · se asignará automáticamente al guardar.</div><div class="form-grid section"><label><span>Cliente</span><input id="noCustomer" value="${draft.customer}" placeholder="Nombre del cliente"></label><label><span>Número de orden del cliente (opcional)</span><input id="noClientOrder" value="${draft.clientOrder}" placeholder="PO / referencia del cliente"></label><label><span>Fecha / entrega</span><input id="noDue" value="${draft.due}" placeholder="Hoy, mañana o fecha"></label><label><span>Tipo de entrega</span><select id="noShip"><option value="pickup" ${draft.shipping==='pickup'?'selected':''}>Recogida del cliente</option><option value="factory" ${draft.shipping==='factory'?'selected':''}>Envío de fábrica</option></select></label><label><span>Condición</span><select id="noCondition"><option value="new" ${draft.condition==='new'?'selected':''}>Pallet nuevo</option><option value="repair" ${draft.condition==='repair'?'selected':''}>Reparación / reacondicionado</option></select></label><label class="wide"><span>Notas de la orden</span><textarea id="noNotes">${draft.notes}</textarea></label></div><div class="dialog-actions"><button type="button" class="btn secondary" id="noCancel">Cancelar</button><button type="button" class="btn" id="noNext">Continuar a descripción →</button></div>`);document.getElementById('noCancel').onclick=closeDialog;document.getElementById('noNext').onclick=()=>{draft.customer=document.getElementById('noCustomer').value.trim();if(!draft.customer){toast('Escribe el cliente.');return}draft.clientOrder=document.getElementById('noClientOrder').value.trim();draft.due=document.getElementById('noDue').value.trim();draft.shipping=document.getElementById('noShip').value;draft.condition=document.getElementById('noCondition').value;draft.notes=document.getElementById('noNotes').value;phase2()}};
  const phase2=()=>{const opts=(state.palletTemplates||[]).map(t=>`<option value="${t.id}" ${draft.templateId===t.id?'selected':''}>${t.name}</option>`).join('');const plan=buildMaterialPlan(draft);openDialog('Nueva orden · Paso 2 de 2',`Orden interna #${draft.internalId} · ${draft.customer}`,`<div class="wizard-steps"><span class="wizard-step done">1 Orden</span><span class="wizard-step active">2 Descripción del pallet</span></div><div class="template-bar"><label><span>Usar plantilla guardada</span><select id="noTemplate"><option value="">— Describir manualmente —</option>${opts}</select></label><button type="button" class="btn ghost" id="noApplyTemplate">Aplicar plantilla</button></div><div class="form-grid section"><label><span>Largo pallet (in)</span><input id="noLength" type="number" min="1" value="${draft.length}"></label><label><span>Ancho pallet (in)</span><input id="noWidth" type="number" min="1" value="${draft.width}"></label><label><span>Cantidad de pallets</span><input id="noQty" type="number" min="1" value="${draft.qty}"></label><label><span>Tipo</span><select id="noWays"><option value="2-way" ${draft.ways==='2-way'?'selected':''}>2-Way</option><option value="4-way" ${draft.ways==='4-way'?'selected':''}>4-Way</option></select></label><label><span>Runners por pallet</span><input id="noRunners" type="number" min="0" value="${draft.runners}"></label><label><span>Calidad de runners</span><select id="noRunnerGrade">${[1,2,3,4].map(g=>`<option value="${g}" ${draft.runnerGrade===g?'selected':''}>#${g}</option>`).join('')}</select></label><label><span>Máximo por pila en LoadMaster</span><input id="noMaxHeight" type="number" min="1" value="${draft.maxHeight}"></label><label class="check-row"><input id="noCanRotate" type="checkbox" ${draft.canRotate?'checked':''}><span>Puede girarse en LoadMaster</span></label></div>${boardRowsHtml('top',draft.topBoards)}${boardRowsHtml('bottom',draft.bottomBoards)}<div class="estimate-box" id="materialEstimate">${materialPlanHtml(plan)}</div><div class="template-save"><label class="check-row"><input id="noSaveTemplate" type="checkbox" ${draft.saveTemplate?'checked':''}><span>Guardar esta descripción como plantilla reutilizable</span></label><input id="noTemplateName" value="${draft.templateName}" placeholder="Ej. 48×40 – Geek Industrial"></div><div class="dialog-actions"><button type="button" class="btn secondary" id="noBack">← Volver</button><button type="button" class="btn" id="noSave">Crear orden #${draft.internalId}</button></div>`);
    const read=()=>{draft.templateId=document.getElementById('noTemplate').value;draft.length=Math.max(1,Number(document.getElementById('noLength').value)||1);draft.width=Math.max(1,Number(document.getElementById('noWidth').value)||1);draft.qty=Math.max(1,Number(document.getElementById('noQty').value)||1);draft.ways=document.getElementById('noWays').value;draft.runners=Math.max(0,Number(document.getElementById('noRunners').value)||0);draft.runnerGrade=Number(document.getElementById('noRunnerGrade').value)||2;draft.maxHeight=Math.max(1,Number(document.getElementById('noMaxHeight').value)||13);draft.canRotate=document.getElementById('noCanRotate').checked;draft.saveTemplate=document.getElementById('noSaveTemplate').checked;draft.templateName=document.getElementById('noTemplateName').value.trim();for(const side of ['top','bottom'])draft[side==='top'?'topBoards':'bottomBoards']=[...document.querySelectorAll(`[data-board-side="${side}"] [data-board-row]`)].map(row=>({width:Number(row.querySelector('[data-board-width]').value)||4,qty:Math.max(0,Number(row.querySelector('[data-board-qty]').value)||0),grade:Number(row.querySelector('[data-board-grade]').value)||2}))};
    const refresh=()=>{read();document.getElementById('materialEstimate').innerHTML=materialPlanHtml(buildMaterialPlan(draft))};['noLength','noWidth','noQty','noRunners','noRunnerGrade'].forEach(id=>document.getElementById(id).addEventListener('input',refresh));document.querySelectorAll('[data-board-row] input,[data-board-row] select').forEach(x=>x.addEventListener('input',refresh));document.querySelectorAll('[data-add-board]').forEach(b=>b.onclick=()=>{read();draft[b.dataset.addBoard==='top'?'topBoards':'bottomBoards'].push({width:4,qty:1,grade:2});phase2()});document.querySelectorAll('[data-remove-board]').forEach(b=>b.onclick=()=>{read();const [side,idx]=b.dataset.removeBoard.split('-');const key=side==='top'?'topBoards':'bottomBoards';draft[key].splice(Number(idx),1);phase2()});
    document.getElementById('noApplyTemplate').onclick=()=>{const t=templateById(document.getElementById('noTemplate').value);if(!t){toast('Selecciona una plantilla.');return}Object.assign(draft,{templateId:t.id,templateName:t.name,length:t.length,width:t.width,condition:t.condition||draft.condition,ways:t.ways,runners:t.runners,runnerGrade:Number(t.runnerGrade)||2,topBoards:normalizeBoardRows(t.topBoards),bottomBoards:normalizeBoardRows(t.bottomBoards),maxHeight:t.maxHeight,canRotate:t.canRotate,saveTemplate:false});phase2()};document.getElementById('noBack').onclick=()=>{read();phase1()};document.getElementById('noSave').onclick=()=>{read();const plan=buildMaterialPlan(draft);if(draft.saveTemplate){if(!draft.templateName){toast('Pon un nombre a la plantilla o desmarca Guardar plantilla.');return}const existing=(state.palletTemplates||[]).find(t=>t.name.toLowerCase()===draft.templateName.toLowerCase());const tpl={id:existing?.id||`TPL-${Date.now()}`,name:draft.templateName,customer:draft.customer,length:draft.length,width:draft.width,condition:draft.condition,ways:draft.ways,runners:draft.runners,runnerGrade:draft.runnerGrade,topBoards:clone(draft.topBoards),bottomBoards:clone(draft.bottomBoards),maxHeight:draft.maxHeight,canRotate:draft.canRotate};if(existing)Object.assign(existing,tpl);else state.palletTemplates.push(tpl)}const id=nextOrderId(),product=`${draft.length}×${draft.width}`;state.orders.unshift({id,clientOrder:draft.clientOrder||'',customer:draft.customer,product,qty:draft.qty,due:draft.due||'Nueva',shipping:draft.shipping,condition:draft.condition,stage:'waiting_material',wood:'AUTO',woodNeed:plan.totalRaw,materialPlan:plan,palletSku:`${product} ${draft.ways}`,notes:draft.notes,palletSpec:{ways:draft.ways,runners:draft.runners,runnerGrade:draft.runnerGrade,topBoards:clone(draft.topBoards),bottomBoards:clone(draft.bottomBoards),templateName:draft.templateName||templateById(draft.templateId)?.name||''},trailerWidth:96,trailerLength:628,loadItems:[{name:product,length:draft.length,width:draft.width,quantity:draft.qty,maxHeight:draft.maxHeight,canRotate:draft.canRotate,type:draft.ways}]});save();closeDialog();toast(`Orden #${id} creada → Producción y visible en Carga.`);navigate('ordenes')};
  };phase1()
}
function materialPlanHtml(p){if(p.shortages?.length)return `<b>Plan automático de material</b><div class="plan-status bad">No alcanza el inventario actual</div><div class="small">${p.shortages.map(x=>`${x.label}: faltan ${x.missing} cortes de ${x.cutLength} in (calidad #${x.grade} o mejor)`).join('<br>')}</div>`;const lines=Object.entries(p.stockTotals||{}).map(([id,n])=>{const w=lumberById(id);return `<li><b>${n}</b> piezas de ${w?.size||id} · calidad #${w?.grade||'?'}</li>`}).join('');return `<b>Plan automático de material</b><div class="plan-status ok">Inventario suficiente · selección automática</div><ul class="material-plan-list">${lines||'<li>No requiere material.</li>'}</ul><div class="small">Total ${p.totalRaw||0} piezas madre · desperdicio lineal aprox. ${Math.round(p.wasteIn||0)} in. El prototipo compara 8/10/12/16 ft y solo usa existencias disponibles.</div>`}
function startCut(id){const o=orderById(id);const plan=buildMaterialPlan({...o.palletSpec,qty:o.qty,length:o.loadItems?.[0]?.length||parseProductMeasure(o.product)?.length,width:o.loadItems?.[0]?.width||parseProductMeasure(o.product)?.width});o.materialPlan=plan;if(plan.shortages.length){save();toast(`No alcanza inventario: ${plan.shortages[0].label}, faltan ${plan.shortages[0].missing}.`);render();return}if(!reserveWood(o)){toast('El inventario cambió y ya no alcanza para este plan.');render();return}o.stage='cutting';addNote(`Orden #${o.id}: plan automático reservado y corte iniciado.`);save();toast('Corte iniciado; madera óptima reservada.');render()}
function finishCut(id){const o=orderById(id);consumeReservedWood(o);o.stage='material_ready';addNote(`Orden #${o.id}: material listo. Fabricación ya puede recogerlo.`);save();toast('Material listo → apareció en Fabricación.');render()}
function startBuild(id){const o=orderById(id);o.stage='building';addNote(`Orden #${o.id}: fabricación iniciada.`);save();toast('Fabricación iniciada.');render()}
function finishBuild(id){const o=orderById(id);o.stage='ready_load';const f=findFinished(o.palletSku);f.qty+=o.qty;f.reserved+=o.qty;addNote(`Orden #${o.id}: ${o.qty} pallets terminados → lista para carga.`);save();toast('Fabricación terminada → orden enviada a Carga.');render()}
function openLoadOrder(id){const o=orderById(id);const pickup=o.shipping==='pickup';openDialog(`Pedido #${o.id}`,`${o.customer}${o.clientOrder?` · Cliente ${o.clientOrder}`:''} · ${pickup?'Recogida del cliente':'Envío de fábrica'}`,`<div class="workflow"><span class="step active">1 Verificar</span><span class="step">2 Optimizar / cargar</span><span class="step">3 Evidencia</span><span class="step">4 Firma</span><span class="step">5 Cerrar</span></div><div class="detail-grid"><div class="detail"><b>Producto</b>${o.product}</div><div class="detail"><b>Cantidad</b>${o.qty} pallets</div><div class="detail"><b>Transporte</b>${pickup?'Cliente trae tráiler':'Fábrica pone chofer y tráiler'}</div><div class="detail"><b>Estado</b>${stageLabel(o.stage)}</div></div><div class="stage-actions"><button type="button" class="btn secondary" id="orderLM">Preparar / optimizar carga</button><button type="button" class="btn" id="markLoading">Marcar cargando</button></div><div class="section evidence"><b>Foto / factura firmada</b><p class="small">La foto es opcional, pero se conserva porque normalmente sirve como evidencia de la factura firmada.</p><input id="evidenceFile" type="file" accept="image/*"><div class="evidence-preview" id="evidencePreview">Sin foto seleccionada.</div></div><div class="section form-grid"><label class="wide"><span>Firma / nombre de quien recibe</span><input id="signatureName" placeholder="Nombre o firma registrada"></label><label class="wide"><span>Notas de carga</span><textarea id="loadNotes">${o.notes||''}</textarea></label></div><div class="dialog-actions"><button type="button" class="btn secondary" id="loadCancel">Cerrar</button><button type="button" class="btn" id="finishDispatch">${pickup?'Completar recogida':'Despachar / en tránsito'}</button></div>`);
  document.getElementById('loadCancel').onclick=closeDialog;document.getElementById('orderLM').onclick=()=>openLoadPreparation(o.id);document.getElementById('markLoading').onclick=()=>{o.stage='loading';save();toast('Pedido marcado como cargando.');};document.getElementById('evidenceFile').onchange=e=>{document.getElementById('evidencePreview').textContent=e.target.files[0]?`Foto seleccionada: ${e.target.files[0].name}`:'Sin foto seleccionada.'};document.getElementById('finishDispatch').onclick=()=>{const sig=document.getElementById('signatureName').value.trim();const hasPhoto=Boolean(document.getElementById('evidenceFile').files[0]);o.notes=document.getElementById('loadNotes').value;if(pickup){completeOrder(o,`${sig?'Firma':'Sin firma'}${hasPhoto?' + foto factura':''}`)}else{o.stage='transit';o.evidence=`${sig?'Firma salida':'Sin firma salida'}${hasPhoto?' + foto':''}`;addNote(`Orden #${o.id}: salió de fábrica y está en tránsito.`);save();closeDialog();toast('Pedido en tránsito.');render()}}
}
function completeDelivery(id){const o=orderById(id);completeOrder(o,(o.evidence||'Salida registrada')+' + entrega confirmada')}
function completeOrder(o,evidence){const f=findFinished(o.palletSku);f.qty=Math.max(0,f.qty-o.qty);f.reserved=Math.max(0,f.reserved-o.qty);state.history.unshift({id:o.id,clientOrder:o.clientOrder||'',customer:o.customer,shipping:o.shipping,completed:'Hoy',evidence:evidence||'Registro completado'});state.orders=state.orders.filter(x=>x.id!==o.id);addNote(`Orden #${o.id}: completada y enviada al historial.`);save();closeDialog();toast('Orden completada → Historial.');render()}
function openLoadPreparation(id){
  const o=orderById(id);if(!o)return;
  const items=loadItemsFor(o);
  if(!items.length){toast('Esta orden no tiene medidas válidas para LoadMaster.');return}
  const rows=items.map((x,i)=>`<tr data-prep-row="${i}"><td><b>${x.name||`${x.length}×${x.width}`}</b><div class="small">${x.length} × ${x.width} in</div></td><td><input class="qty-locked" type="number" value="${Number(x.quantity)||1}" readonly aria-label="Cantidad bloqueada"></td><td><input data-prep-height type="number" min="1" value="${Math.max(1,Number(x.maxHeight)||13)}" aria-label="Altura máxima"></td><td class="center"><input data-prep-rotate type="checkbox" ${x.canRotate!==false?'checked':''} aria-label="Se puede girar"></td></tr>`).join('');
  openDialog(`Preparar carga #${o.id}`,`${o.customer} · ${loadTotal(items)} pallets enviados automáticamente desde la orden`,
  `<div class="notification info"><b>Datos conectados.</b> Las medidas y cantidades vienen de la orden y no necesitas volver a escribirlas. Antes de abrir LoadMaster revisa únicamente la altura máxima y si cada medida puede girar.</div>
  <div class="prep-trailer"><label><span>Ancho del tráiler (in)</span><input id="prepTrailerWidth" type="number" min="1" value="${Number(o.trailerWidth)||96}"></label><label><span>Largo del tráiler (in)</span><input id="prepTrailerLength" type="number" min="1" value="${Number(o.trailerLength)||628}"></label></div>
  <div class="table-wrap prep-table"><table><thead><tr><th>Medida</th><th>Cantidad</th><th>Altura máx.</th><th>Girar</th></tr></thead><tbody>${rows}</tbody></table></div>
  <div class="prep-note"><b>${loadTotal(items)} pallets</b> · ${items.length} medida${items.length===1?'':'s'} · cantidad protegida por la orden</div>
  <div class="dialog-actions"><button type="button" class="btn secondary" id="prepCancel">Volver</button><button type="button" class="btn" id="prepLaunch">Abrir LoadMaster a pantalla completa</button></div>`);
  document.getElementById('prepCancel').onclick=()=>{closeDialog();openLoadOrder(id)};
  document.getElementById('prepLaunch').onclick=()=>{
    const prepared=items.map((item,i)=>{const row=document.querySelector(`[data-prep-row="${i}"]`);return {...item,quantity:Number(item.quantity)||1,maxHeight:Math.max(1,Number(row.querySelector('[data-prep-height]').value)||1),canRotate:row.querySelector('[data-prep-rotate]').checked,type:item.type||'4-way'};});
    o.loadItems=clone(prepared);o.trailerWidth=Math.max(1,Number(document.getElementById('prepTrailerWidth').value)||96);o.trailerLength=Math.max(1,Number(document.getElementById('prepTrailerLength').value)||628);save();
    const payload={version:1,source:'Pallet Operations',orderId:o.id,customer:o.customer,shipping:o.shipping,trailer:{width:o.trailerWidth,length:o.trailerLength},items:prepared,returnUrl:'index.html#carga',createdAt:new Date().toISOString()};
    localStorage.setItem(LM_HANDOFF,JSON.stringify(payload));
    window.location.href=`loadmaster.html?platform=1&order=${encodeURIComponent(o.id)}`;
  };
}
function openLoadMaster(){
  const payload={version:1,source:'Pallet Operations',orderId:'manual',customer:'Carga manual',trailer:{width:96,length:628},items:[],returnUrl:'index.html#carga',createdAt:new Date().toISOString()};
  localStorage.setItem(LM_HANDOFF,JSON.stringify(payload));window.location.href='loadmaster.html?platform=1';
}

document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
document.getElementById('resetDemo').addEventListener('click',()=>{if(confirm('¿Restablecer todos los datos del prototipo?')){state=normalizeState(structuredClone(initialState));save();toast('Demo restablecida.');render()}});
if(!views[currentView])currentView='inicio';
render();
