const fs=require('fs'),vm=require('vm');
let src=fs.readFileSync('app.js','utf8');
src=src.replace(/new App\(\);\s*$/,'globalThis.__LM={LoadEngine,runPortfolioSearch,validateLayout,solutionDistance};');
const sandbox={console,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},localStorage:{getItem:()=>null,setItem:()=>{}},document:{getElementById:()=>({}),querySelector:()=>null},window:{addEventListener:()=>{}},navigator:{},crypto:{randomUUID:()=>String(Math.random())}};
vm.createContext(sandbox);vm.runInContext(src,sandbox);
const {LoadEngine,runPortfolioSearch,validateLayout,solutionDistance}=sandbox.__LM;
const mk=(id,w,l,qty=20)=>({id,name:id,w,l,x:0,y:700,qty,type:'4-way',canRotate:true,locked:false});
const input=[];
for(let i=0;i<4;i++)input.push(mk(`a${i}`,42,42));
for(let i=0;i<4;i++)input.push(mk(`b${i}`,34,42));
for(let i=0;i<4;i++)input.push(mk(`c${i}`,28,28));
const trailer={width:96,length:190};
const baseline=new LoadEngine(trailer,{timeLimitMs:10000,seedOffset:0,profile:'large'}).optimize(input);
if(!baseline.ok||!baseline.solutions.length)throw new Error('No produjo base');
const result=runPortfolioSearch(input,trailer,{totalTimeMs:12000,baselineSolutions:baseline.solutions});
if(!result.ok||!result.solutions.length)throw new Error('Portafolio vacío');
if(result.attemptedProfiles!==4)throw new Error('No configuró cuatro perfiles');
const base=baseline.solutions[0],best=result.solutions[0];
if(best.loadedPallets<base.loadedPallets||best.loadedStacks<base.loadedStacks)throw new Error('El portafolio empeoró la base');
for(const sol of result.solutions)if(!validateLayout(sol.stacks,trailer).ok)throw new Error('Layout inválido');
if(result.solutions.length>1&&solutionDistance(result.solutions[0],result.solutions[1],trailer)<0.01)throw new Error('Opciones duplicadas');
console.log('PASS v5.8: cuatro búsquedas independientes, diversidad y piso de calidad preservado.');
