const fs=require('fs'),vm=require('vm');
let src=fs.readFileSync('app.js','utf8');
src=src.replace(/new App\(\);\s*$/,'globalThis.__LM={LoadEngine,validateLayout,Geometry};');
const sandbox={console,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},localStorage:{getItem:()=>null,setItem:()=>{}},document:{getElementById:()=>({}),querySelector:()=>null},window:{addEventListener:()=>{}},navigator:{},crypto:{randomUUID:()=>String(Math.random())}};
vm.createContext(sandbox);vm.runInContext(src,sandbox);
const {LoadEngine,validateLayout}=sandbox.__LM;
const trailer={width:96,length:160};
let id=0;const mk=(w,l,name)=>({id:`s${++id}`,name,w,l,x:0,y:0,qty:20,type:'4-way',canRotate:true,locked:false});
const input=[];
for(let r=0;r<4;r++)input.push(mk(34,28,'34'),mk(34,28,'34'),mk(28,28,'28'));
for(let r=0;r<1;r++)input.push(mk(42,32,'42'),mk(42,32,'42'));
const engine=new LoadEngine(trailer,{timeLimitMs:6000,seedOffset:510,profile:'rows'});
const plans=engine.structuralProfiles(input);
if(plans.length<4)throw new Error('El Motor V2 no generó suficientes estructuras globales');
const outputs=plans.map(p=>({p,out:engine.structuralRowPack(p.order,[],input,p.mode)})).filter(x=>x.out);
if(!outputs.length)throw new Error('El Motor V2 no produjo ningún plano estructural');
const best=outputs.sort((a,b)=>a.out.unplaced.length-b.out.unplaced.length)[0];
if(best.out.unplaced.length!==0)throw new Error(`El Motor V2 dejó ${best.out.unplaced.length} pilas fuera en un patrón estructural conocido`);
if(!validateLayout(best.out.stacks,trailer).ok)throw new Error('El Motor V2 produjo un plano inválido');
console.log('PASS v5.10: planificación global por estructuras, filas completas y layout válido.');
